In [10]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [5]:
df = pd.read_csv("glossi-dataset-v1.csv")
df.head()

,date,min_dryness,max_dryness,min_heaviness,max_heaviness,shampoo_used_today,conditioner_used_today,leave_in_amt,sweat,humidity,bath_intensity,wind_exposure
0,2025-07-13,5.0,10.0,2.0,6.0,yes,yes,0.0,4.0,82,10.0,7.0
1,2025-07-14,3.0,4.0,4.0,5.0,no,yes,3.0,1.0,72,8.0,5.0
2,2025-07-15,4.0,5.0,4.0,6.0,no,no,2.5,3.0,78,7.0,6.0
3,2025-07-16,3.0,4.5,4.0,5.0,no,no,0.0,3.5,76,7.0,6.5
4,2025-07-17,2.0,6.0,3.0,7.0,no,no,0.0,4.0,87,7.5,1.0

In [9]:
cleaned_df = df.drop(columns=["date", "max_heaviness","max_dryness", "min_heaviness"], axis=1)
cleaned_df.head()

,min_dryness,shampoo_used_today,conditioner_used_today,leave_in_amt,sweat,humidity,bath_intensity,wind_exposure
0,5.0,yes,yes,0.0,4.0,82,10.0,7.0
1,3.0,no,yes,3.0,1.0,72,8.0,5.0
2,4.0,no,no,2.5,3.0,78,7.0,6.0
3,3.0,no,no,0.0,3.5,76,7.0,6.5
4,2.0,no,no,0.0,4.0,87,7.5,1.0

In [27]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_copy = cleaned_df.copy()
df_copy["shampoo_used_today"] = le.fit_transform(df_copy["shampoo_used_today"])
df_copy["conditioner_used_today"] = le.fit_transform(df_copy["conditioner_used_today"])
df_copy.head()

,min_dryness,shampoo_used_today,conditioner_used_today,leave_in_amt,sweat,humidity,bath_intensity,wind_exposure
0,5.0,1,1,0.0,4.0,82,10.0,7.0
1,3.0,0,1,3.0,1.0,72,8.0,5.0
2,4.0,0,0,2.5,3.0,78,7.0,6.0
3,3.0,0,0,0.0,3.5,76,7.0,6.5
4,2.0,0,0,0.0,4.0,87,7.5,1.0

In [28]:
X = df_copy.drop(columns=["min_dryness"], axis=1)
y = df_copy["min_dryness"]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print("R2 Score: ", r2_score(y_test, lr.predict(X_test)))
print("MSE: ", mean_squared_error(y_test, lr.predict(X_test)))

R2 Score:  0.49389830590874906
MSE:  0.502868000847341

In [31]:
print("Coefficients: ", lr.coef_)
print("Intercept: ", lr.intercept_)

Coefficients:  [ 0.53021863  0.16230531 -0.21417387  0.03747662 -0.01787766 -0.09956396
  0.10925777]
Intercept:  4.20783117458634