In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, root_mean_squared_error, explained_variance_score

In [2]:
df = pd.read_csv("glossi-dataset-v1.csv")
df.head()

,date,min_dryness,max_dryness,min_heaviness,max_heaviness,shampoo_used_today,conditioner_used_today,leave_in_amt,sweat,humidity,bath_intensity,wind_exposure
0,2025-07-13,5.0,10.0,2.0,6.0,yes,yes,0.0,4.0,82,10.0,7.0
1,2025-07-14,3.0,4.0,4.0,5.0,no,yes,3.0,1.0,72,8.0,5.0
2,2025-07-15,4.0,5.0,4.0,6.0,no,no,2.5,3.0,78,7.0,6.0
3,2025-07-16,3.0,4.5,4.0,5.0,no,no,0.0,3.5,76,7.0,6.5
4,2025-07-17,2.0,6.0,3.0,7.0,no,no,0.0,4.0,87,7.5,1.0

In [3]:
# Feature Engineering 'Average Dryness
df["average_dryness"] = (df["max_dryness"] + df["min_dryness"]) / 2
cleaned_df = df.drop(columns=["date", "max_heaviness","max_dryness", "min_heaviness", "min_dryness"], axis=1)
cleaned_df.head()
print(cleaned_df.describe())

       leave_in_amt       sweat    humidity  bath_intensity  wind_exposure  \
count    112.000000  112.000000  112.000000      112.000000     112.000000
mean       1.561607    1.225893   74.294643        5.030357       2.943750
std        1.945623    1.547375    4.989427        3.540826       2.144164
min        0.000000    0.000000   63.000000        0.000000       0.000000
25%        0.000000    0.000000   71.000000        0.000000       1.000000
50%        0.000000    0.750000   74.000000        6.000000       3.000000
75%        3.500000    2.000000   78.000000        7.000000       4.000000
max        5.000000    6.000000   87.000000       10.000000      10.000000

       average_dryness
count       112.000000
mean          3.486607
std           0.922857
min           1.750000
25%           2.750000
50%           3.500000
75%           4.000000
max           7.500000

In [4]:
# encode categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df_copy = cleaned_df.copy()
df_copy["shampoo_used_today"] = le.fit_transform(df_copy["shampoo_used_today"])
df_copy["conditioner_used_today"] = le.fit_transform(df_copy["conditioner_used_today"])
df_copy.head()

,shampoo_used_today,conditioner_used_today,leave_in_amt,sweat,humidity,bath_intensity,wind_exposure,average_dryness
0,1,1,0.0,4.0,82,10.0,7.0,7.50
1,0,1,3.0,1.0,72,8.0,5.0,3.50
2,0,0,2.5,3.0,78,7.0,6.0,4.50
3,0,0,0.0,3.5,76,7.0,6.5,3.75
4,0,0,0.0,4.0,87,7.5,1.0,4.00

In [6]:
X = df_copy.drop(columns=["average_dryness"], axis=1)
y = df_copy["average_dryness"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

# =======================================================
#                       EVALUATION
# =======================================================
print("R2 Score: ", r2_score(y_test, lr.predict(X_test)))
print("MSE: ", mean_squared_error(y_test, lr.predict(X_test)))
print("MAE: ", mean_absolute_error(y_test, lr.predict(X_test)))
print("RMSE: ", root_mean_squared_error(y_test, lr.predict(X_test)))
print("Explained Variance Score: ", explained_variance_score(y_test, lr.predict(X_test)))

R2 Score:  0.40240082566198
MSE:  0.7029867489580465
MAE:  0.5328669897213666
RMSE:  0.8384430505156844
Explained Variance Score:  0.4531095763392293

### Previous Metrics (Target: min_dryness)
R2 Score:  0.49389830590874906

MSE:  0.502868000847341

MAE:  0.5705126874430705

RMSE:  0.7091318642166216

Explained Variance Score:  0.4939475909608376

In [9]:
print("Coefficients: ", lr.coef_)
print("Intercept: ", lr.intercept_)

Coefficients:  [ 0.64707195 -0.02906673 -0.2646154  -0.03489914 -0.01720086 -0.01400846
  0.06599629]
Intercept:  4.914931200064931

### Previous Values

Coefficients:  [ 0.53021863  0.16230531 -0.21417387  0.03747662 -0.01787766 -0.09956396
  0.10925777]
  
Intercept:  4.20783117458634